# Generated by Django 2.0.2 on 2018-03-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='customusermodel',
            old_name='_is_admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='customusermodel',
            old_name='_is_staff',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table='custom_users',
        ),
    ]
