# Generated by Django 2.0.2 on 2018-03-13 10:18

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20180313_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 10, 18, 35, 979479, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
