# Generated by Django 2.0.2 on 2018-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_auto_20180313_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
